# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1)),
                ('currency', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=4)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('mid', models.DecimalField(decimal_places=12, default='0.0', max_digits=16)),
            ],
        ),
    ]
