# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
    ]
